export default {
  FETCH_AUTHENTICATION_TOKEN_NEW: "FETCH_AUTHENTICATION_TOKEN_NEW",
  FETCH_AUTHENTICATION_TOKEN_VALIDATE_WITH_LOGIN:
    "FETCH_AUTHENTICATION_TOKEN_VALIDATE_WITH_LOGIN",
  FETCH_AUTHENTICATION_SESSION_NEW: "FETCH_AUTHENTICATION_SESSION_NEW",
  FETCH_ACCOUNT: "FETCH_ACCOUNT",
};
