export default {
  FETCH_TOP_RATED_MOVIES: "FETCH_TOP_RATED_MOVIES",
  FETCH_UPCOMING_MOVIE: "FETCH_UPCOMING_MOVIE",
  FETCH_NOW_PLAYING_MOVIES: "FETCH_NOW_PLAYING_MOVIES",
  FETCH_GENRES_MOVIE: "FETCH_GENRES_MOVIE",
};
