export default {
  FETCH_NOW_PLAYING_MOVIES_REQUEST: "FETCH_NOW_PLAYING_MOVIES_REQUEST",
  FETCH_NOW_PLAYING_MOVIES_SUCCESS: "FETCH_NOW_PLAYING_MOVIES_SUCCESS",
  FETCH_NOW_PLAYING_MOVIES_FAILURE: "FETCH_NOW_PLAYING_MOVIES_FAILURE",
};
