export default {
  FETCH_POPULAR_MOVIES_REQUEST: "FETCH_POPULAR_MOVIES_REQUEST",
  FETCH_POPULAR_MOVIES_SUCCESS: "FETCH_POPULAR_MOVIES_SUCCESS",
  FETCH_POPULAR_MOVIES_FAILURE: "FETCH_POPULAR_MOVIES_FAILURE",
};
