export default {
  FETCH_SEARCH_MOVIE_REQUEST: "FETCH_SEARCH_MOVIE_REQUEST",
  FETCH_SEARCH_MOVIE_SUCCESS: "FETCH_SEARCH_MOVIE_SUCCESS",
  FETCH_SEARCH_MOVIE_FAILURE: "FETCH_SEARCH_MOVIE_FAILURE",
};
