export default {
  FETCH_TOP_RATED_MOVIES_REQUEST: "FETCH_TOP_RATED_MOVIES_REQUEST",
  FETCH_TOP_RATED_MOVIES_SUCCESS: "FETCH_TOP_RATED_MOVIES_SUCCESS",
  FETCH_TOP_RATED_MOVIES_FAILURE: "FETCH_TOP_RATED_MOVIES_FAILURE",
};
