export default {
  FETCH_UPCOMING_MOVIE_REQUEST: "FETCH_UPCOMING_MOVIE_REQUEST",
  FETCH_UPCOMING_MOVIE_SUCCESS: "FETCH_UPCOMING_MOVIE_SUCCESS",
  FETCH_UPCOMING_MOVIE_FAILURE: "FETCH_UPCOMING_MOVIE_FAILURE",
};
