export default {
  FETCH_WATCHLIST_MOVIE_REQUEST: "FETCH_WATCHLIST_MOVIE_REQUEST",
  FETCH_WATCHLIST_MOVIE_SUCCESS: "FETCH_WATCHLIST_MOVIE_SUCCESS",
  FETCH_WATCHLIST_MOVIE_FAILURE: "FETCH_WATCHLIST_MOVIE_FAILURE",
};
